In [1]:
1.
import numpy as np
a = np.arange(1,10).reshape(3,3)
b = np.arange(9,0,-1).reshape(3,3)
print(a+b)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [2]:
2.
a = np.arange(1,10).reshape(3,3)
b = np.arange(9,0,-1).reshape(3,3)
print(a*b)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [3]:
3.
a = np.arange(1,10).reshape(3,3)
print(a.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [4]:
4.
my_str = "Hello this Is an Example With cased letters"
word = [words.lower() for words in my_str.split()]
word.sort()
for i in word:
    print(i)

an
cased
example
hello
is
letters
this
with


In [5]:
5.
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
my_str = "Hello!!!, he said ---and went."
no_punc = ''
for punc in my_str:
    if punc not in punctuations:
        no_punc = no_punc + punc
print(no_punc)

Hello he said and went
